### PR TITLE
The task is finished

### PR DESCRIPTION
**Pull request by gwu358**
The task is finished. It can be run by following the instructions in instruction.txt.

### CODE REVIEW

**Comment by brentnd** [comment]
@gwu358 thanks for the submission.

Closing this and we will follow up with you.

**Comment by brentnd** [comment]
@gwu358 looks like this code works to produce the expected output. Would you be able to re-work this using a more object-oriented approach?

**Comment by gwu358** [comment]
Hi, I just modified the code using an object-oriented approach. Let me know if this is what you want or not.

**Comment by brentnd** [comment]
@gwu358 thanks for the follow up to the review.

Closing this and we will follow up with you.

**Pull request closed without merging**
